name: xdlm
backbone: dit  # dit / dimamba / hf_dit
parameterization: align
time_conditioning: False
sample_force_float64: False
T: 0  # 0 (continuous time) / 1000 
subs_masking: False
causal_attention: False # to use DitBlockCausal (but modified, and recognizes is_causal=False)
ignore_bos: False
loss_type: elbo
k1: 0.1
sample_start_k1_zero: False
